# -*- coding: utf-8 -*-
"""tools_export_theme_tokens.py - export the app's Catppuccin Mocha palette
(gui/styles.py COLORS) as CSS custom properties, so material rendered outside
Qt (tutorial videos, docs, web reports) matches the running app and cannot
drift when the theme changes.

Usage:  python tools_export_theme_tokens.py [-o OUT.css]
        (no argument = docs/videos/app-tour/styles/mocha.css)

Loads gui/styles.py BY PATH rather than importing the `gui` package, so this
stays GUI-free (no PySide6 import) regardless of what gui/__init__.py grows.
The output is generated - edit gui/styles.py and re-run, never hand-edit the
CSS."""
import argparse
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STYLES_PY = os.path.join(HERE, "gui", "styles.py")
DEFAULT_OUT = os.path.join(HERE, "docs", "videos", "app-tour",
                           "styles", "mocha.css")


def load_colors(path=STYLES_PY):
    """Return gui/styles.py's COLORS dict without importing the gui package."""
    spec = importlib.util.spec_from_file_location("_mebp_styles", path)
    if spec is None or spec.loader is None:
        raise SystemExit("could not load %s" % path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    colors = getattr(mod, "COLORS", None)
    if not isinstance(colors, dict) or not colors:
        raise SystemExit("%s defines no usable COLORS dict" % path)
    return colors


def to_css(colors, source_rel="gui/styles.py"):
    lines = [
        "/* GENERATED by tools_export_theme_tokens.py - DO NOT EDIT.",
        " * Source of truth: %s (COLORS)." % source_rel,
        " * Re-run the script after changing the theme.",
        " */",
        ":root {",
    ]
    for key in sorted(colors):
        value = colors[key]
        if not isinstance(value, str) or not value.startswith("#"):
            continue
        token = key.replace("_", "-")
        lines.append("  --mocha-%s: %s;" % (token, value))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", default=DEFAULT_OUT,
                    help="output .css path (default: %(default)s)")
    args = ap.parse_args(argv)

    colors = load_colors()
    css = to_css(colors)

    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(css)

    n = css.count("--mocha-")
    print("wrote %d tokens -> %s" % (n, args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
